name: TheThuum
main: io.github.dailystruggle.thethuum.Plugin
version: ${project.version}
api-version: 1.13
softdepend: [PlaceholderAPI]

commands:
  shout:
    description: speak dragon
    permission: thuum.shout
    usage: |
      /shout
  thuum:
    description: "thuum root command"
    permission: thuum.see
    usage: |
      /thuum

permissions:
  thuum.see:
    default: op
    description: "view thuum commands"
  thuum.reload:
    default: op
    description: "reload config.yml"