name: TheThuum
main: io.github.dailystruggle.thethuum.Plugin
version: ${project.version}
api-version: 1.13
softdepend: [PlaceholderAPI]

commands:
  shout:
    description: speak dragon
    permission: thuum.shout
    usage: |
      /shout